# Generated by Django 5.2.8 on 2025-11-06 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LetterRoom",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("owner", models.CharField(max_length=50)),
                ("title", models.CharField(max_length=100)),
                (
                    "cover_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="letterrooms/covers/"
                    ),
                ),
                ("open_at", models.DateTimeField()),
                (
                    "visibility",
                    models.CharField(
                        choices=[
                            ("PUBLIC_ALL", "전체 공개"),
                            ("PUBLIC_FRIENDS", "친구만"),
                        ],
                        default="PUBLIC_ALL",
                        max_length=20,
                    ),
                ),
                (
                    "write_permission",
                    models.CharField(
                        choices=[
                            ("WRITE_ALL", "누구나 작성 가능"),
                            ("WRITE_FRIENDS", "친구만"),
                            ("WRITE_INVITED", "초대 링크만"),
                        ],
                        default="WRITE_ALL",
                        max_length=20,
                    ),
                ),
                ("allow_anonymous", models.BooleanField(default=True)),
                (
                    "share_code",
                    models.CharField(editable=False, max_length=12, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RoomLetter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("author", models.CharField(max_length=50)),
                ("is_anonymous", models.BooleanField(default=False)),
                (
                    "font_style",
                    models.CharField(
                        choices=[
                            ("BASIC", "기본체"),
                            ("ROUND", "둥근체"),
                            ("SOFT", "부드러운체"),
                            ("ELEGANT", "우아한체"),
                            ("MODERN", "모던체"),
                            ("WARM", "따뜻한체"),
                        ],
                        default="BASIC",
                        max_length=20,
                    ),
                ),
                (
                    "paper_theme",
                    models.CharField(
                        choices=[
                            ("WHITE", "흰색"),
                            ("PURPLE", "보라색"),
                            ("PINK_HEART", "핑크 하트"),
                            ("BLUE_SKY", "파란 하늘"),
                            ("GREEN_CLOVER", "초록 클로버"),
                            ("PEACH_BLOSSOM", "복숭아 꽃"),
                        ],
                        default="WHITE",
                        max_length=20,
                    ),
                ),
                ("content", models.TextField()),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="letters/"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "letterroom",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="letters",
                        to="letterrooms.letterroom",
                    ),
                ),
            ],
            options={
                "ordering": ["-id"],
            },
        ),
    ]
