# Generated by Django 5.2.6 on 2025-11-13 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("letterrooms", "0002_alter_letterroom_owner_alter_roomletter_author"),
    ]

    operations = [
        migrations.AddField(
            model_name="letterroom",
            name="opened_noti_sent",
            field=models.BooleanField(default=False),
        ),
    ]
