# Generated by Django 5.2.6 on 2025-11-10 14:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DirectLetter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "font_style",
                    models.CharField(
                        choices=[
                            ("BASIC", "기본체"),
                            ("ROUND", "둥근체"),
                            ("SOFT", "부드러운체"),
                            ("ELEGANT", "우아한체"),
                            ("MODERN", "모던체"),
                            ("WARM", "따뜻git한체"),
                        ],
                        default="BASIC",
                        max_length=20,
                    ),
                ),
                (
                    "paper_theme",
                    models.CharField(
                        choices=[
                            ("WHITE", "흰색"),
                            ("PURPLE", "보라색"),
                            ("PINK_HEART", "핑크 하트"),
                            ("BLUE_SKY", "파란 하늘"),
                            ("GREEN_CLOVER", "초록 클로버"),
                            ("PEACH_BLOSSOM", "복숭아 꽃"),
                        ],
                        default="WHITE",
                        max_length=20,
                    ),
                ),
                ("content", models.TextField()),
                ("open_at", models.DateTimeField()),
                (
                    "image1",
                    models.ImageField(
                        blank=True, null=True, upload_to="direct_letters/"
                    ),
                ),
                (
                    "image2",
                    models.ImageField(
                        blank=True, null=True, upload_to="direct_letters/"
                    ),
                ),
                (
                    "image3",
                    models.ImageField(
                        blank=True, null=True, upload_to="direct_letters/"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "receiver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="received_direct_letters",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_direct_letters",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
