# Generated by Django 5.2.8 on 2025-11-11 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("letters", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="directletter",
            name="font_style",
            field=models.CharField(
                choices=[
                    ("BASIC", "기본체"),
                    ("ROUND", "둥근체"),
                    ("SOFT", "부드러운체"),
                    ("ELEGANT", "우아한체"),
                    ("MODERN", "모던체"),
                    ("WARM", "따뜻한체"),
                ],
                default="BASIC",
                max_length=20,
            ),
        ),
    ]
