# Generated by Django 5.2.6 on 2025-11-13 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("letters", "0002_alter_directletter_font_style"),
    ]

    operations = [
        migrations.AddField(
            model_name="directletter",
            name="opened_noti_sent",
            field=models.BooleanField(default=False),
        ),
    ]
